---
- name: Update repository and Upgrade packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Setup timezone to America/New_York
  timezone:
    name: "{{ set_timezone }}"

- name: Install utilities
  apt:
    name:
      - git
      - wget
      - curl
      - vim
      - nfs-common
      - apt-transport-https
      - ca-certificates
      - cloud-init
    state: present

- name: Set authorized keys taken from url
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ copy_local_key }}"

- name: Disable password authentication for root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin prohibit-password"
    