---
- name: Ensure old versions of Docker are not installed.
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
  ignore_errors: "{{ docker_apt_ignore_key_error }}"

- name: Install Docker.
  apt:
    name: "docker-ce={{ docker_version }}"
    state: present
  notify: restart docker

- name: Hold docker package.
  shell: apt-mark hold docker-ce

- name: Deploy Docker daemon.json.
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers
